name: Build and Deploy Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    environment: 
      name: testing
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${ { secrets.DATABASE_URL } }
      SECRET_KEY: ${ { secrets.SECRET_KEY } }
      ALGORITHM: ${ { secrets.ALGORITHM } }
      ACCESS_TOKEN_EXPIRES_MINUTES: ${ { secrets.ACCESS_TOKEN_EXPIRES_MINUTES } }
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest
